### ISSUE TITLE
Change font size with keyboard

### ISSUE THREAD

**Issue by igr-santos** [nossas/slate-editor#2]
Today not possible change font size with keyboard, only when `<Enter>` pressed

**Comment by gabrielrtakeda** [comment]
@igr-santos To increase the font size, you can use the keyboard shortcut with target text selected.

https://github.com/ourcities/slate-editor/tree/master/src/package/plugins/slate-font-size-plugin#keyboard-shortcut

Please, can you test it on a linux keyboard?

| Action              | Keyboard Shortcut                                                           |
|---------------|-------------------------------------------------------|
| **Increase**:  | <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>+</kbd> |
| **Decrease**: | <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>-</kbd> |

About the <kbd>Enter</kbd> on input, I don't really know if it is a bug or, a feature.
It needs to handle the `onChange` prop here:

https://github.com/ourcities/slate-editor/blob/master/src/package/plugins/slate-font-size-plugin/FontSizeInput.js#L38-L44

But, the value prop of input is handled by editor's state...

Can you suggest any solution about this?

**Comment by abobwhite** [comment]
FYI - in my recent testing on Windows I also see this issue. For some reason when debugging it seems like the `ctrl` and `alt` are never true at the same time. This must be a limitation of slate itself. May I suggest instead use the shortcuts used in Microsoft Word? This is what I did in my own slate editor and it works fine. The combination is `isMod + <` or `isMod + >` which technically becomes `isMod + isShift + ,` or `isMod + isShift + .`

Here is the relevant code:
```
if (data.isMod && data.isShift) {
    if (data.key === ',' || data.key === '.') { // < or >
      const increase = data.key !== ',';
      // Increase/Decrease logic
    }
}
```

**Comment by gabrielrtakeda** [comment]
Awesome suggestion @abobwhite!
