### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by tashburn** [nossas/slate-editor#20]
http://slate-editor.reboo-staging.org/

Error: "An unhandled lowlevel error occurred. The application logs may have details."

**Comment by gabrielrtakeda** [comment]
Oops, I was changed the url of the server.. heh
Follow the new URL: http://slate-editor.staging.bonde.org/

Thanks for opened the issue. For now, I'll close this but, if have another issue, open it again ;)

**Comment by bkniffler** [comment]
Its down again :(

**Comment by lpirola** [comment]
@bkniffler we are back, thanks to report!
