### ISSUE TITLE
`yarn start` results in error

### ISSUE THREAD

**Issue by thundergolfer** [nossas/slate-editor#25]
#### Steps to reproduce

1. Clone the repo
2. `cd` into `/slate-editor`
3. Run `yarn start`

#### Result 

```
yarn start
yarn start v0.23.4
$ react-scripts start
sh: react-scripts: command not found
error Command failed with exit code 127.
```

**Comment by gabrielrtakeda** [comment]
Hi @thundergolfer, thanks for the issue!
Before you run `yarn start`, you need to run `yarn install` to install all the dependencies that our repo needs.. (:
I forgot to add the step to install on the docs 😛 
I'll add it (:

If even running `yarn install` before `yarn start` the error persists, please, don't hesitate and reopen this issue.
