### ISSUE TITLE
Publish plugins to npm?

### ISSUE THREAD

**Issue by oyeanuj** [nossas/slate-editor#3]
Hi @gabrielrtakeda, Thank you for putting it out there. The plugins you have are very helpful, wondering if you intend to publish the plugins through NPM so that they are more widely discoverable (and through Slate's Readme)?

**Comment by gabrielrtakeda** [comment]
Hi @oyeanuj, I thank you for the comment. The next step to conclude this slatejs rich text editor implementation was exactly to publish it into NPM and, some improvements (any help are welcome) but, not the plugins themselves separately. But according to your suggestion, I will publish the plugins separately to makes possible the installation of the plugins that the developer wants.

**Comment by oyeanuj** [comment]
awesome, thank you!

**Comment by gabrielrtakeda** [comment]
https://www.npmjs.com/package/slate-editor

Just install it with:
- `yarn add slate-editor` or `npm install slate-editor`
