### ISSUE TITLE
'npm start' does not work locally

### ISSUE THREAD

**Issue by abobwhite** [nossas/slate-editor#37]
I am trying to work on a PR and I can't get the editor to run locally. Everything appears to install just fine, though. A window opens at `http://localhost:3000/` but nothing loads. Any ideas would be appreciated.

Node: 6.10.0
npm: 3.10.6
OS: Windows 7 Enterprise

Here are the console errors:

```
warning.js:35 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check your code at index.js:11.
    in Example (at index.js:6)
printWarning @ warning.js:35
warning @ warning.js:59
createElement @ ReactElementValidator.js:192
Example @ index.js:25
(anonymous) @ ReactCompositeComponent.js:305
measureLifeCyclePerf @ ReactCompositeComponent.js:75
_constructComponentWithoutOwner @ ReactCompositeComponent.js:304
_constructComponent @ ReactCompositeComponent.js:279
mountComponent @ ReactCompositeComponent.js:187
mountComponent @ ReactReconciler.js:45
performInitialMount @ ReactCompositeComponent.js:370
mountComponent @ ReactCompositeComponent.js:257
mountComponent @ ReactReconciler.js:45
mountComponentIntoNode @ ReactMount.js:104
perform @ Transaction.js:143
batchedMountComponentIntoNode @ ReactMount.js:126
perform @ Transaction.js:143
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:319
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
(anonymous) @ index.js:19
(anonymous) @ bundle.js:1363
__webpack_require__ @ bundle.js:556
fn @ bundle.js:87
(anonymous) @ multi_main:3
(anonymous) @ bundle.js:589
__webpack_require__ @ bundle.js:556
(anonymous) @ bundle.js:579
(anonymous) @ bundle.js:582
invariant.js:44 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Example`.
    at invariant (invariant.js:44)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (instantiateReactComponent.js:74)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:366)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:257)
    at Object.mountComponent (ReactReconciler.js:45)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:370)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:257)
    at Object.mountComponent (ReactReconciler.js:45)
    at mountComponentIntoNode (ReactMount.js:104)
    at ReactReconcileTransaction.perform (Transaction.js:143)
```

**Comment by abobwhite** [comment]
I figured it out! I removed "^" from all the dependencies in package.json because those minor version upgrades since this was last updated looks like it caused imports to break.

I have been under the impression that as a community, we're frowning upon using anything but exact dependencies in npm? Maybe this would work if I was using yarn? I'd like to work a PR for this but want to get some clarification around this first. Maybe it's just an update to the README?

**Comment by lpirola** [comment]
Thanks @abobwhite, @gabrielrtakeda will try to resolve this bug and at the same time will upgrade slatejs #35.

**Comment by gabrielrtakeda** [comment]
Hi @abobwhite! I am glad that you have contacted us! I think it is really good that the community help improving the repository and I am very happy that caught your eyes! We really need people that want to contribute too and your help is very appreciate!

About the bug issue with npm, I tested locally installing the dependencies with npm (v5.0.4) and the problem is really with npm, because when installing with yarn, we already the version of packages that is working actually in the project (yarn.lock file).. I have dived a little more deep into the code and founded that the error was produced by the way that we are using the `react-router` package which have changed its API.. I will push a commit to fix this and will have a look into the PR that you have opened..

Again, thanks for the contribution! (:

**Comment by abobwhite** [comment]
Thanks @gabrielrtakeda and @lpirola I went ahead and tried yarn yesterday and got it to work in the meantime. Thanks for updating npm support, too :)

**Comment by gabrielrtakeda** [comment]
We thank you for the help.

**Comment by abobwhite** [comment]
I would suggest while fixing this to remove "^" from the npm dependencies. While in theory, it's handy, so many libraries are not respecting sem-ver and so minor/patch versions are making incompatible, breaking changes. Which in turn make this library slave to those versions. I would recommend using no qualifier on the dependencies and just keeping them exact so you know it will work.

Also - I would recommend including in the README which version(s) of node/npm are compatible with the development of this editor.

**Comment by gabrielrtakeda** [comment]
Rebase 👇
