### ISSUE TITLE
Insert link at beginning of line results in deuplicate text

### ISSUE THREAD

**Issue by mfbx9da4** [nossas/slate-editor#42]
![yjcryzhd2a](https://user-images.githubusercontent.com/1690659/30984099-da4457fa-a438-11e7-84e8-af27471f6895.gif)

**Comment by gabrielrtakeda** [comment]
Hi @mfbx9da4!
We will treat this as soon as possible but, we really appreciate a PR too! 😃 
If you want to challenge yourself to solve this bug, we will be very glad to review your PR! If you have any problem to setup your local environment, we can help you. 😉 

And, thanks for the the bug report.

**Comment by mfbx9da4** [comment]
Okay I think I found the issue give me a sec

**Comment by mfbx9da4** [comment]
Current logic:

1. **Click "Insert Link" button**
2. **Shift text** If the selected text is either at the beginning of a line or immediately after an inline node (ie `startOffset === 0` then insert the selected text and with a space before it before wrapping the text with an inline link.
3. **Create the Link Node**. Wrap the text with inline link and openModal.
4. **Unshift text** Delete the space before the text.
5. Save link data from modal input

Step 2 and 4 is done because otherwise the selection / state ends up in a weird state where `startOffset` and `endOffset` are 0. I believe the focus finishes up before the inline link node, at the beginning of the line. Subsequently step 5 isn't able to update the inline node as there is no inline node to update. I am unable to manipulate the selection manually such that the selection is inside the inline node. 

Do you know why this final weird state is produced and why we have to do the hack in step 2 and 4?

As for the bug, in step 2, you were reinserting the offset `anchorText` which is all the text until the next inline node, not just the text under selection ([offending line](https://github.com/nossas/slate-editor/blob/master/src/package/plugins/slate-link-plugin/LinkUtils.js#L49)). Instead you need to get the selected text with something like `anchorText.text.substring(s,e)`. Here is the fix below:

```js
const endOffset = state.selection.endOffset
const selectedText = state.anchorText.text.substring(startOffset, endOffset)

// fix offset 0 selection:
// add a single white space and select forward white space
if (startOffset === 0) {
      const space = ' '
      transform
        .insertText(space + selectedText)
        .moveOffsetsTo(space.length, selectedText.length + space.length)
}
```

Also in [`updateLinkStrategy`](https://github.com/nossas/slate-editor/blob/master/src/package/plugins/slate-link-plugin/LinkUtils.js#L24) why are you doing 

`.extend(text.length * -1)` instead of `.extend(text.length)`

Valeu 🇧🇷 ❤️
