### ISSUE TITLE
React 16 doesn't support propTypes

### ISSUE THREAD

**Issue by theskillwithin** [nossas/slate-editor#53]
https://github.com/nossas/slate-editor/blob/987143c9c43b9a2a7a44deac8d1c10d951af91e8/src/package/plugins/slate-color-plugin/DraggableColorPicker.js#L39

**Comment by gabrielrtakeda** [comment]
Hi @theskillwithin, thanks for opening the issue!
This will be fixed be fixed when the PR #51 was merged.
