### ISSUE TITLE
Generating duplicate IDs slate-image-plugin-button 

### ISSUE THREAD

**Issue by lpirola** [nossas/slate-editor#6]

**Comment by gabrielrtakeda** [comment]
@lpirola This occurs when try to add multiple images?

**Comment by gabrielrtakeda** [comment]
# Tutorial

**[BONDE][SlateEditor] Insert Multiple Images Inline**

[![Insert Multiple Images Inline](https://img.youtube.com/vi/p5k9De7baDA/0.jpg)](https://www.youtube.com/watch?v=p5k9De7baDA)
