### ISSUE TITLE
Put plugins in separate packages

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [nossas/slate-editor#62]
Most of the plugins (`slate-bold-plugin`, etc.) could be reused by other projects not using `slate-editor` itself - it would be nice to have a way to depend on them directly, instead of including the whole package.

I think most rich-text editors using `slate` have similar code - it could be a great thing for the community to be able to reuse that.

**Comment by gabrielrtakeda** [comment]
Hi @tomasz-sodzawiczny! We had already though about to put the plugins in separate packages, to avoid the mandatory installation of the whole `slate-editor` package for those who already have their own `slate` implementation but, had not been prioritized so far... I will discuss with the team about to turn the `slate-editor` into a monorepo, publishing the plugins in separate packages to npm but, keeping the current behaviour for those who use the whole implementation of `slate-editor`...

**Comment by tomasz-sodzawiczny** [comment]
@gabrielrtakeda Great! Let me know if you'll need any help with that - I could probably find a day or two to help you with it.

We also have a set of similar plugins in our project, we can share them too. :)

**Comment by gabrielrtakeda** [comment]
Awesome @tomasz-sodzawiczny! I am here to notify you that I got a little time to proceed with this issue. The idea is to use [lerna](https://github.com/lerna/lerna) to distribute plugins into separate packages and publish it individually to npm.

I will push some commits next that initiate the process to separate the plugins into its package individually. I believe that this issue will be resolved soon. (:

**Comment by gabrielrtakeda** [comment]
@tomasz-sodzawiczny, the plugins was published to npm separately..
You can check all plugins [here in slate-editor scoped packages list](https://www.npmjs.com/settings/slate-editor/packages).
Each plugin have its own docs and usage example:
https://github.com/nossas/slate-editor/tree/develop/packages

If you have other plugins, we will be very happy to receive a pull-request including it.
I will close this issue considering that the main goal was reached.
Feel free to reopen if you deem it necessary.
