### ISSUE TITLE
Saving to Database and Displaying content 

### ISSUE THREAD

**Issue by KatiuscaH** [nossas/slate-editor#75]
I don't know where to post this and if is not the place, I'm sorry.
Hello, I'm a newbie using Nossas and I have a doubt. How I can save data to database and displaying the content when I visit the editor again?. How I send this content to an API and how convert to Json the data to save them?. I'm very confused because I don't find a official documentation and the page is down.

**Comment by gabrielrtakeda** [comment]
Hi @KatiuscaH, our editor is based on [`slate`](https://docs.slatejs.org/) that is a framework to build rich text editors... You can find more informations in [Slate docs page](https://docs.slatejs.org/).

To save to a database, see the [**Saving to a Database**](https://docs.slatejs.org/walkthroughs/saving-to-a-database) section of theirs documentation.

**Comment by KatiuscaH** [comment]
Thanks a lot. But I have another trouble. Today I installed the editor with some plugins and the icons in the buttons never was displayed. The button are small and I can't see them. How solve this? I taked a css class and I replaced the background of button with an image and set the width and heigth but is not the best solution.

**Comment by gabrielrtakeda** [comment]
@KatiuscaH you can define [classNames](https://github.com/nossas/slate-editor/blob/develop/packages/slate-editor-example/src/example/pages/Home.js#L40-L45) or [styles](https://github.com/nossas/slate-editor/blob/develop/packages/slate-editor-example/src/example/pages/Home.js#L46-L72) and pass like [this](https://github.com/nossas/slate-editor/blob/develop/packages/slate-editor-example/src/example/pages/Home.js#L90-L96) and [this](https://github.com/nossas/slate-editor/blob/develop/packages/slate-editor-example/src/example/pages/Home.js#L100) respectively.

All plugin components accepts `className` and `style` props.

**Comment by KatiuscaH** [comment]
Thanks a lot!
