### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by denzils** [nossas/slate-editor#77]
Hello,

I don't understand how to do the image upload. What am I supposed to do with the signingURL? I have an AWS s3 account, but I just need help putting it all together. Thank you!

**Comment by gabrielrtakeda** [comment]
Hi @denzils! You need to expose an endpoint like [this](https://github.com/nossas/bonde-server/blob/master/app/controllers/uploads_controller.rb). This example was made in Ruby on Rails. You need to adapt it using the programming language that you want. After that, you need to `export` the `REACT_APP_API_URL` and `REACT_APP_SIGNING_URL_ENDPOINT` environment variables like:

- `REACT_APP_API_URL`: `https://api.bonde.org`
- `REACT_APP_SIGNING_URL_ENDPOINT`: `/uploads`

Making this, the `slate-editor` image plugin, will identify it to upload and use the signed image url.

**Comment by lpirola** [comment]
@denzils an working example could be found at these issue: https://github.com/nossas/slate-editor/issues/80

If you still have issues, let me know.
