### ISSUE TITLE
can't insert image

### ISSUE THREAD

**Issue by YunyunZhai** [nossas/slate-editor#80]

**Comment by lpirola** [comment]
Hi @YunyunZhai to image upload works you will need to configure a server, if you share more details, maybe I could help.

**Comment by lpirola** [comment]
Hellor @YunyunZhai, here there are a working example of a rails app as api rest.

https://github.com/nossas/bonde-server/blob/develop/app/controllers/uploads_controller.rb

If you still have some misconception about how create your own server code, let me know.
